# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  - board: seeeduino_xiao_ble
    shield: non_nemo_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_DONGLE_SCREEN_AMBIENT_LIGHT=y
    shield: non_nemo_dongle dongle_screen
  - board: seeeduino_xiao_ble
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    shield: non_nemo_left 
  - board: seeeduino_xiao_ble
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    shield: non_nemo_right 
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: non-nemo-settings-reset
