manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: urob
      url-base: https://github.com/urob
    # Prospector
    - name: carrefinho
      url-base: https://github.com/carrefinho
    # Dongle Screen
    - name: janpfischer
      url-base: https://github.com/janpfischer
    # TB2086
    - name: tb2086
      url-base: https://github.com/Thunderbird2086
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: main
    - name: prospector-zmk-module
      remote: carrefinho
      revision: main
      path: modules/prospector-zmk-module
    - name: zmk-dongle-screen
      remote: janpfischer
      revision: main
      path: modules/zmk-dongle-screen
  self:
    path: config
